CONSTRUCTING TENSORS

Tensor:- A tensor is a multidimensional array

In [1]:
import torch

# Create a tensor of ones with 3 elements
a = torch.ones(3)
print("Initial tensor a:", a)


Initial tensor a: tensor([1., 1., 1.])


In [2]:
# Access the second element (index 1)
print("a[1]:", a[1])

a[1]: tensor(1.)


In [3]:
# Convert the tensor element to a Python float
print("float(a[1]):", float(a[1]))

float(a[1]): 1.0


In [5]:
# Modify the third element (index 2) to 2.0
a[2] = 2.0
print("Modified tensor a:", a)

Modified tensor a: tensor([1., 1., 2.])


**Creating a 1D Tensor for Points (Flat Representation)**

In [6]:
import torch

# Initialize a tensor of zeros with 6 elements
points = torch.zeros(6)

# Manually set point coordinates
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

print("1D Tensor of points (flat representation):", points)


1D Tensor of points (flat representation): tensor([4., 1., 5., 3., 2., 1.])


**Creating the Same Tensor Using a Python List**

In [7]:
# Defining the same points directly using torch.tensor and a list
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
print("1D Tensor of points (using list):", points)

1D Tensor of points (using list): tensor([4., 1., 5., 3., 2., 1.])


In [8]:
# Access the first point's coordinates (x=4.0, y=1.0)
x1 = float(points[0])
y1 = float(points[1])
print("First point coordinates: (", x1, ",", y1, ")")


First point coordinates: ( 4.0 , 1.0 )


**Using a 2D Tensor**

In [9]:
# Creating a 2D tensor where each row represents a point (x, y)
points = torch.tensor([
    [4.0, 1.0],
    [5.0, 3.0],
    [2.0, 1.0]
])

print("2D Tensor of points:\n", points)

2D Tensor of points:
 tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


In [10]:
# Checking the Shape of the Tensor
print("Shape of points tensor:", points.shape)

Shape of points tensor: torch.Size([3, 2])


In [11]:
# Initializing a 2D Tensor of Zeros
# Create a 2D tensor of zeros with shape (3, 2)
points = torch.zeros(3, 2)
print("2D Tensor initialized with zeros:\n", points)


2D Tensor initialized with zeros:
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [12]:
#Accessing an Individual Element (x, y of a Point)
# Create the points again for clarity
points = torch.tensor([
    [4.0, 1.0],
    [5.0, 3.0],
    [2.0, 1.0]
])

# Access the second coordinate (y) of the first point (index [0, 1])
print("Second coordinate of first point:", points[0, 1])  # Output: tensor(1.)


Second coordinate of first point: tensor(1.)


**Indexing Tensors**

Indexing Tensors:- Indexing tensors means selecting specific elements, rows, columns, or slices from a tensor, just like you do with Python lists or NumPy arrays.

In [13]:
some_list = list(range(6))

print("Full list:", some_list[:])
print("Elements from index 1 to 3:", some_list[1:4])
print("Elements from index 1 to end:", some_list[1:])
print("Elements from start to index 3:", some_list[:4])
print("All except last:", some_list[:-1])
print("Elements from index 1 to 3 with step 2:", some_list[1:4:2])


Full list: [0, 1, 2, 3, 4, 5]
Elements from index 1 to 3: [1, 2, 3]
Elements from index 1 to end: [1, 2, 3, 4, 5]
Elements from start to index 3: [0, 1, 2, 3]
All except last: [0, 1, 2, 3, 4]
Elements from index 1 to 3 with step 2: [1, 3]


**NAMED TENSORS**

Named Tensor:- Named tensors are tensors where each dimension has a name, rather than just a position

In [14]:
import torch

# Create a dummy image tensor: 3 channels (RGB), 5x5 image
img_t = torch.randn(3, 5, 5)  

# Create a dummy batch of 2 images: [batch, channels, rows, columns]
batch_t = torch.randn(2, 3, 5, 5)

# Grayscale weights 
weights = torch.tensor([0.2126, 0.7152, 0.0722])

img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)

print("Naive grayscale image shape:", img_gray_naive.shape)
print("Naive grayscale batch shape:", batch_gray_naive.shape)



Naive grayscale image shape: torch.Size([5, 5])
Naive grayscale batch shape: torch.Size([2, 5, 5])


In [15]:
# Weighted Grayscale Conversion with Broadcasting
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
img_gray_weighted = (img_t * unsqueezed_weights).sum(-3)
batch_gray_weighted = (batch_t * unsqueezed_weights).sum(-3)

print("Weighted grayscale image shape:", img_gray_weighted.shape)
print("Weighted grayscale batch shape:", batch_gray_weighted.shape)


Weighted grayscale image shape: torch.Size([5, 5])
Weighted grayscale batch shape: torch.Size([2, 5, 5])


In [16]:
# Using einsum for Compact Weighted Sum

img_gray_einsum = torch.einsum('chw,c->hw', img_t, weights)
batch_gray_einsum = torch.einsum('nchw,c->nhw', batch_t, weights)

print("Einsum grayscale batch shape:", batch_gray_einsum.shape)


Einsum grayscale batch shape: torch.Size([2, 5, 5])


**Named Tensors**

In [17]:
# Create named weights
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])

# Add names to img_t and batch_t
img_named = img_t.refine_names('channels', 'rows', 'columns')
batch_named = batch_t.refine_names(None, 'channels', 'rows', 'columns')

print("Image tensor names:", img_named.names)
print("Batch tensor names:", batch_named.names)


Image tensor names: ('channels', 'rows', 'columns')
Batch tensor names: (None, 'channels', 'rows', 'columns')


/tmp/ipykernel_36/2323760085.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /pytorch/c10/core/TensorImpl.h:1935.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


In [18]:
# Aligning Weights with Image Tensor
# Align weights to match img_named dimensions
weights_aligned = weights_named.align_as(img_named)

# Perform weighted sum using names
gray_named = (img_named * weights_aligned).sum('channels')

print("Named grayscale image shape:", gray_named.shape)
print("Named grayscale image names:", gray_named.names)


Named grayscale image shape: torch.Size([5, 5])
Named grayscale image names: ('rows', 'columns')


In [19]:
# Remove names to get back to regular tensor
gray_plain = gray_named.rename(None)

print("Plain grayscale shape:", gray_plain.shape)
print("Plain grayscale names:", gray_plain.names)


Plain grayscale shape: torch.Size([5, 5])
Plain grayscale names: (None, None)


**Managing a tensor’s dtype attribute**

The dtype of a tensor defines the kind of numeric data it stores

In [21]:
import torch

# Create a 10x2 tensor of ones with double precision (float64)
double_points = torch.ones(10, 2, dtype=torch.double)

# Create a 2x2 tensor with short integers (int16)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
print("short_points dtype:", short_points.dtype)
#This code Specify dtype during tensor creation for the desired precision. 

short_points dtype: torch.int16


** Cast Tensor to Another Type**

In [22]:
# Using .double() and .short()

double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)
print(double_points)
print(short_points)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


In [23]:
# Using .to() Method
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)
print(double_points)
print(short_points)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


**Mixed-Type Operations**

In [24]:
# Create a double precision tensor
points_64 = torch.rand(5, dtype=torch.double)

# Cast it to short (int16)
points_short = points_64.to(torch.short)

# Multiply double and short tensors
result = points_64 * points_short
print(result)


tensor([0., 0., 0., 0., 0.], dtype=torch.float64)


**The Tensor API**

The Tensor API is the collection of functions, methods, and operations that you can use to create, manipulate, and perform computations on tensors in PyTorch.

In [25]:
import torch

# Create a 3x2 tensor of ones
a = torch.ones(3, 2)

print("Original tensor shape:", a.shape)
print(a)


Original tensor shape: torch.Size([3, 2])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [26]:
# Transpose Using torch Module Function
# Transpose using torch module function
a_torch_transpose = torch.transpose(a, 0, 1)

print("\nTransposed tensor (using torch.transpose):")
print(a_torch_transpose)
print("Shape:", a_torch_transpose.shape)



Transposed tensor (using torch.transpose):
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Shape: torch.Size([2, 3])


In [27]:
# Transpose Using Tensor Method

# Transpose using tensor method
a_method_transpose = a.transpose(0, 1)

print("\nTransposed tensor (using a.transpose):")
print(a_method_transpose)
print("Shape:", a_method_transpose.shape)



Transposed tensor (using a.transpose):
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Shape: torch.Size([2, 3])


**Indexing into storage**

A PyTorch tensor is a view on top of a storage.
The storage is a 1D contiguous block of memory where the tensor's values are actually stored.
The tensor keeps metadata (shape, strides, offset) to interpret the data correctly as multi-dimensional.



In [28]:
import torch

# Define a 3x2 tensor (3 rows, 2 columns)
points = torch.tensor([
    [4.0, 1.0],
    [5.0, 3.0],
    [2.0, 1.0]
])

print("Original tensor:\n", points)


Original tensor:
 tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


In [29]:
# Access the Tensor's Storage

points_storage = points.storage()

print("\nTensor Storage Content:")
for i in range(len(points_storage)):
    print(points_storage[i])


Tensor Storage Content:
4.0
1.0
5.0
3.0
2.0
1.0


/tmp/ipykernel_36/3370387277.py:3: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage = points.storage()


In [30]:
# Access specific elements from storage

print("\nFirst element in storage (index 0):", points_storage[0])
print("Second element in storage (index 1):", points_storage[1])


First element in storage (index 0): 4.0
Second element in storage (index 1): 1.0


In [31]:
# Modify the Storage
points_storage[0] = 2.0

print("\nTensor after modifying storage:\n", points)

#Changing the storage directly modifies the tensor because the tensor references the storage.


Tensor after modifying storage:
 tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])


**In-Place Operations**

In-place operations are tensor operations that modify the original tensor directly instead of returning a new tensor.
They are identified by a trailing underscore (_) in the method name.

In [32]:
import torch
a = torch.ones(3, 2)
print("Original tensor:\n", a)


Original tensor:
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [33]:
# Zero out all elements in-place
a.zero_()
print("\nTensor after in-place zeroing (a.zero_()):\n", a)



Tensor after in-place zeroing (a.zero_()):
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


**Tensor metadata: Size, offset, and stride**

In order to index into a storage, tensors rely on a few pieces of information that,
together with their storage, unequivocally define them: size, offset, and stride.


In [34]:
import torch

points = torch.tensor([
    [4.0, 1.0],
    [5.0, 3.0],
    [2.0, 1.0]
])
print("Original Tensor:\n", points)

Original Tensor:
 tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


In [35]:
# Extract a Subtensor
second_point = points[1]

print("\nSecond point (view):", second_point)


Second point (view): tensor([5., 3.])


In [36]:
# Inspect Storage Offset, Size, and Stride
# Storage offset tells where in the 1D storage the view starts
print("Storage offset:", second_point.storage_offset())

# Size (Shape)
print("Size:", second_point.size())

# Stride: how many elements to skip in storage per index increase
print("Stride:", second_point.stride())


Storage offset: 2
Size: torch.Size([2])
Stride: (1,)


In [37]:
# Change the first element of second_point
second_point[0] = 10.0

print("\nModified Tensor:\n", points)


Modified Tensor:
 tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])


In [38]:
#  Use clone() to Avoid Side Effects
# Create a copy (no shared storage)
points = torch.tensor([
    [4.0, 1.0],
    [5.0, 3.0],
    [2.0, 1.0]
])

second_point_clone = points[1].clone()
second_point_clone[0] = 10.0

print("\nAfter cloning and modifying second_point_clone:")
print("Original points tensor remains unchanged:\n", points)


After cloning and modifying second_point_clone:
Original points tensor remains unchanged:
 tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


**Transposing without copying**

Transposing a tensor means flipping its dimensions.
In PyTorch, t() and transpose() do not create a new storage; they create a view with different shape and stride, but share the same underlying data.

In [39]:
import torch

points = torch.tensor([
    [4.0, 1.0],
    [5.0, 3.0],
    [2.0, 1.0]
])

print("Original Tensor:\n", points)


Original Tensor:
 tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


In [40]:
# Transpose: swap rows and columns
points_t = points.t()
print("\nTransposed Tensor:\n", points_t)


Transposed Tensor:
 tensor([[4., 5., 2.],
        [1., 3., 1.]])


In [41]:
# Verify they share the same storage
# Check if Storage is Shared
print("\nDo 'points' and 'points_t' share storage?")
print(id(points.storage()) == id(points_t.storage()))



Do 'points' and 'points_t' share storage?
True


In [42]:
# Compare Strides
print("\nOriginal tensor stride:", points.stride())   # (2, 1)
print("Transposed tensor stride:", points_t.stride()) # (1, 2)


Original tensor stride: (2, 1)
Transposed tensor stride: (1, 2)


**Transposing in Higher Dimensions in PyTorch**

In PyTorch, you can transpose any two dimensions of an N-dimensional tensor using the transpose(dim0, dim1) function.
This operation swaps the dimensions and modifies the strides accordingly, but does not copy data.

In [43]:
import torch
some_t = torch.ones(3, 4, 5)

print("Original Tensor Shape:", some_t.shape)
print("Original Tensor Stride:", some_t.stride())


Original Tensor Shape: torch.Size([3, 4, 5])
Original Tensor Stride: (20, 5, 1)


In [44]:
# Transpose First and Last Dimensions
transpose_t = some_t.transpose(0, 2)

print("\nTransposed Tensor Shape:", transpose_t.shape)
print("Transposed Tensor Stride:", transpose_t.stride())


Transposed Tensor Shape: torch.Size([5, 4, 3])
Transposed Tensor Stride: (1, 5, 20)


**Contiguous Tensors**


* A contiguous tensor is a tensor whose elements are stored in memory in a row-major order (C-style).This means the stride is consistent with the shape for direct memory access without gaps or reordering.



* Some PyTorch operations (like view()) require contiguous memory.If the tensor is non-contiguous, PyTorch will raise an error and ask you to call .contiguous() to get a copy with a proper memory layout.




In [45]:
import torch

# Original tensor
points = torch.tensor([
    [4.0, 1.0],
    [5.0, 3.0],
    [2.0, 1.0]
])

print("Original Tensor:\n", points)
print("Is 'points' contiguous?", points.is_contiguous())


Original Tensor:
 tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
Is 'points' contiguous? True


In [46]:
# Transpose: swap rows and columns
points_t = points.t()

print("\nTransposed Tensor:\n", points_t)
print("Is 'points_t' contiguous?", points_t.is_contiguous())



Transposed Tensor:
 tensor([[4., 5., 2.],
        [1., 3., 1.]])
Is 'points_t' contiguous? False


In [47]:
# Check Strides and Storage

print("\nOriginal Tensor Stride:", points.stride())    # (2, 1)
print("Transposed Tensor Stride:", points_t.stride())  # (1, 2)

print("\nOriginal Storage:", list(points.storage()))
print("Transposed Storage (shared):", list(points_t.storage()))



Original Tensor Stride: (2, 1)
Transposed Tensor Stride: (1, 2)

Original Storage: [4.0, 1.0, 5.0, 3.0, 2.0, 1.0]
Transposed Storage (shared): [4.0, 1.0, 5.0, 3.0, 2.0, 1.0]


In [48]:
# Make the Transposed Tensor Contiguous

points_t_cont = points_t.contiguous()

print("\nContiguous Copy of Transposed Tensor:\n", points_t_cont)
print("Is 'points_t_cont' contiguous?", points_t_cont.is_contiguous())

print("\nNew Stride:", points_t_cont.stride())
print("New Storage:", list(points_t_cont.storage()))


Contiguous Copy of Transposed Tensor:
 tensor([[4., 5., 2.],
        [1., 3., 1.]])
Is 'points_t_cont' contiguous? True

New Stride: (3, 1)
New Storage: [4.0, 5.0, 2.0, 1.0, 3.0, 1.0]


**Managing a tensor’s device attribute**

Each PyTorch tensor has a device attribute that specifies where the tensor is stored and operated upon:
CPU – Regular computer RAM (default for most systems)
GPU – Graphics Processing Unit (for acceleration with CUDA or ROCm)

In [1]:
import torch

# Check if GPU is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device:", device)

Using device: cuda


In [2]:
# Create Tensor Directly on GPU
points_gpu = torch.tensor([[4.0, 1.0],
                           [5.0, 3.0],
                           [2.0, 1.0]], device=device)

print("Tensor on device (GPU if available):")
print(points_gpu)

Tensor on device (GPU if available):
tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')


In [3]:
# Create Tensor on CPU and Move to GPU
# Create tensor on CPU
points_cpu = torch.tensor([[4.0, 1.0],
                           [5.0, 3.0],
                           [2.0, 1.0]])

# Move tensor to device (GPU/CPU)
points_gpu_copy = points_cpu.to(device)

print("Tensor copied from CPU to device:")
print(points_gpu_copy)


Tensor copied from CPU to device:
tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')


In [5]:
# Perform Multiplication on the Device

result_gpu = 2 * points_gpu_copy

print("After multiplication by 2 (on GPU if available):")
print(result_gpu)

After multiplication by 2 (on GPU if available):
tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]], device='cuda:0')


In [6]:
# Perform Addition on the Device
result_gpu = result_gpu + 4

print("After adding 4 (on GPU if available):")
print(result_gpu)

After adding 4 (on GPU if available):
tensor([[12.,  6.],
        [14., 10.],
        [ 8.,  6.]], device='cuda:0')


In [7]:
# Move Result Back to CPU
result_cpu = result_gpu.to('cpu')
print("Result moved back to CPU:")
print(result_cpu)

Result moved back to CPU:
tensor([[12.,  6.],
        [14., 10.],
        [ 8.,  6.]])


**NumPy interoperability**

* PyTorch provides seamless interoperability with NumPy.
* We can easily:
    * Convert PyTorch tensors to NumPy arrays using .numpy()
    *  Convert NumPy arrays to PyTorch tensors using torch.from_numpy()

In [8]:
# Convert PyTorch Tensor to NumPy Array
import torch
import numpy as np

# Create a tensor of ones (3x4)
points = torch.ones(3, 4)

# Convert tensor to NumPy array
points_np = points.numpy()

print("NumPy array from tensor:")
print(points_np)
print("Type:", type(points_np))


NumPy array from tensor:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Type: <class 'numpy.ndarray'>


In [9]:
# Convert NumPy Array Back to PyTorch Tensor
new_tensor = torch.from_numpy(points_np)

print("New PyTorch tensor from NumPy array:")
print(new_tensor)

New PyTorch tensor from NumPy array:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


**Serializing tensors**

Serialization is the process of saving tensors to disk and loading them back later.

In [13]:
import torch
import os
import h5py

# Create a sample tensor
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print("Original Tensor:")
print(points)


Original Tensor:
tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


In [14]:
# Create directory if not exists
os.makedirs('/kaggle/working/data/p1ch3', exist_ok=True)

# Save tensor
torch.save(points, '/kaggle/working/data/p1ch3/ourpoints.t')
print("Tensor saved using torch.save() to '/kaggle/working/data/p1ch3/ourpoints.t'")


Tensor saved using torch.save() to '/kaggle/working/data/p1ch3/ourpoints.t'


In [15]:
with open('/kaggle/working/data/p1ch3/ourpoints.t', 'wb') as f:
    torch.save(points, f)
print("Tensor saved using file descriptor.")

Tensor saved using file descriptor.


In [16]:
# Load tensor back
points_loaded = torch.load('/kaggle/working/data/p1ch3/ourpoints.t')
print("Loaded Tensor:")
print(points_loaded)

Loaded Tensor:
tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


In [17]:
# Save tensor as HDF5 (convert to NumPy)
with h5py.File('/kaggle/working/data/p1ch3/ourpoints.hdf5', 'w') as f:
    dset = f.create_dataset('coords', data=points.numpy())
print("Tensor saved in HDF5 format to '/kaggle/working/data/p1ch3/ourpoints.hdf5'")


Tensor saved in HDF5 format to '/kaggle/working/data/p1ch3/ourpoints.hdf5'


In [18]:
# Load specific rows from HDF5
with h5py.File('/kaggle/working/data/p1ch3/ourpoints.hdf5', 'r') as f:
    dset = f['coords']
    last_points_np = dset[-2:]  # Load last 2 rows (lazy load)

print("Last two points from HDF5 (NumPy format):")
print(last_points_np)


Last two points from HDF5 (NumPy format):
[[5. 3.]
 [2. 1.]]


In [19]:
# Convert NumPy to PyTorch tensor
last_points = torch.from_numpy(last_points_np)

print("Last two points as PyTorch tensor:")
print(last_points)


Last two points as PyTorch tensor:
tensor([[5., 3.],
        [2., 1.]])


I learned from this chapter how to efficiently manage PyTorch tensors, including operations related to storage, in-place modification, and device management (CPU/GPU). I also understood how to convert tensors to NumPy arrays and back, enabling easy integration with other Python libraries. Additionally, I practiced saving and loading tensors using both torch.save() and HDF5 with h5py, storing all files in /kaggle/working/data/p1ch3/.